# https://docs.github.com/en/enterprise-cloud@latest/actions/sharing-automations/creating-workflow-templates-for-your-organization#creating-a-workflow-template
name: Test reusable workflow that uses a local file

on:  
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: |
        task validate
    - name: Test with pytest
      run: |
        task test -- kmom01
